# Flujo de trabajo CI/CD para un sistema de gobernanza basado en blockchain

name: Governance System CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4

      # Paso 2: Instalar Node.js para manejar scripts frontend
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Paso 3: Instalar dependencias (sin cambiar de directorio)
      - name: Instalar dependencias
        run: npm install

      # Paso 4: Ejecutar linters y pruebas del frontend
      - name: Ejecutar linters y pruebas del frontend
        run: |
          npm run lint
          npm run test

      # Paso 5: Instalar Hardhat
      - name: Instalar Hardhat
        run: |
          npm install --save-dev hardhat

      # Paso 6: Compilar contratos Solidity
      - name: Compilar contratos Solidity
        run: |
          npx hardhat compile

      # Paso 7: Ejecutar pruebas de contratos
      - name: Ejecutar pruebas de contratos
        run: |
          npx hardhat test

      # Paso 8: Notificar éxito
      - name: Notificar éxito
        run: echo "¡El sistema de gobernanza ha sido construido y desplegado exitosamente!"
